In [4]:
import pandas as pd
df = pd.read_csv('mine.csv')
print(df)
#print(df.info())

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [5]:
import pandas as pd
df = pd.read_csv('mine.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      29 non-null     object
 2   Pulse     30 non-null     float64
 3   Maxpulse  29 non-null     float64
 4   Calories  27 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 1.3+ KB
None

In [8]:
import pandas as pd
df = pd.read_csv('mine.csv')
new_df = df.dropna()
print(new_df)
print(new_df.info())

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
14        60  2023/10/15'  120.0     100.0     240.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
<class 'pandas.core.frame.DataFrame'>
Index: 22 entries, 0 to 28
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  22 non-null     int64
 1   Date      22 non-null     object
 2   Pulse     22 non-null     float64
 3   Maxpulse  22 non-null     float64
 4   Calories  22 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 1.0+ KB
None

In [12]:
import pandas as pd
df = pd.read_csv('mine.csv')
df.dropna(inplace = True)
print(df.to_string())

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
14        60  2023/10/15'  120.0     100.0     240.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2

In [14]:
#Replace NULL values with the number 130:

import pandas as pd

df = pd.read_csv('mine.csv')

df.fillna(130, inplace = True)

print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0     130.0
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0     130.0     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'  130.0     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0     130.0
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0     130.0
22        60          130  130.0     108.0     230.8
23        60  2023/10/24'  134.0     130.0     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          130   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0     130.0

In [15]:
import pandas as pd
df = pd.read_csv('mine.csv')
df.fillna({"Maxpulse" : 130}, inplace = True)
print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0     130.0     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0     130.0     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [20]:
import pandas as pd
df = pd.read_csv('mine.csv')
x = df["Calories"].mean()
print(x)
df.fillna({"Calories" : x}, inplace = True)
print(df)

302.8592592592592
    Duration         Date  Pulse  Maxpulse    Calories
0         60  2023/10/01'  110.0     130.0  409.100000
1         60  2023/10/02'  117.0     145.0  479.000000
2         60  2023/10/03'  103.0     135.0  340.300000
3         45  2023/10/04'  109.0     175.0  282.400000
4         45  2023/10/05'  117.0     150.0  405.100000
5         60  2023/10/06'  103.0     125.0  300.000000
6         60  2023/10/07'  110.0     135.0  374.000000
7        400  2023/10/08'  114.0     133.0  302.859259
8         60  2023/10/09'  112.0     126.0  193.800000
9         30  2023/10/10'  102.0     147.0  234.800000
10        60  2023/10/11'  100.0     129.0  375.300000
11        60  2023/10/12'  109.0     131.0  345.600000
12        60  2023/10/13'  103.0     136.0  239.200000
13        60  2023/10/15'  120.0       NaN  240.800000
14        60  2023/10/15'  120.0     100.0  240.800000
15        60  2023/10/16'    NaN     101.0  243.800000
16        60  2023/10/17'  127.0     102.0  380.200000
17        45     20231018  142.0     103.0  241.400000
18        60  2023/10/19'  151.0     104.0  302.859259
19        60  2023/10/20'  162.0     105.0  300.900000
20        60  2023/10/21'  100.0     106.0  280.000000
21        60  2023/10/22'  103.0     107.0  302.859259
22        60          NaN  130.0     108.0  230.800000
23        60  2023/10/24'  134.0       NaN  239.700000
24        60  2023/10/25'  132.0     110.0  236.900000
25        60  2023/10/26'  135.0     118.0  278.800000
26        60  2023/10/27'  137.0     119.0  212.900000
27        60  2023/10/28'  138.0     121.0  345.900000
28        60  2023/10/29'  139.0     122.0  345.200000
29        60          NaN   92.0     125.0  380.500000
30        60  2023/10/31'   94.0     126.0  302.859259

In [21]:
import pandas as pd
df = pd.read_csv('mine.csv')
y = df["Maxpulse"].median()
print(y)
df.fillna({"Maxpulse" : y}, inplace = True)
print(df)

125.0
    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0     125.0     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0     125.0     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [27]:
import pandas as pd
df = pd.read_csv('mine.csv')
z = df["Pulse"].mode()[0]
print(z)
df.fillna({"Pulse" : z}, inplace = True)
print(df)

103.0
    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'  103.0     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [28]:
import pandas as pd
df = pd.read_csv('mine.csv')
df['Date'] = pd.to_datetime(df['Date'], format = 'mixed')
df.dropna(subset = ['Date'], inplace = True)
print(df)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2023-10-01  110.0     130.0     409.1
1         60 2023-10-02  117.0     145.0     479.0
2         60 2023-10-03  103.0     135.0     340.3
3         45 2023-10-04  109.0     175.0     282.4
4         45 2023-10-05  117.0     150.0     405.1
5         60 2023-10-06  103.0     125.0     300.0
6         60 2023-10-07  110.0     135.0     374.0
7        400 2023-10-08  114.0     133.0       NaN
8         60 2023-10-09  112.0     126.0     193.8
9         30 2023-10-10  102.0     147.0     234.8
10        60 2023-10-11  100.0     129.0     375.3
11        60 2023-10-12  109.0     131.0     345.6
12        60 2023-10-13  103.0     136.0     239.2
13        60 2023-10-15  120.0       NaN     240.8
14        60 2023-10-15  120.0     100.0     240.8
15        60 2023-10-16    NaN     101.0     243.8
16        60 2023-10-17  127.0     102.0     380.2
17        45 2023-10-18  142.0     103.0     241.4
18        60 2023-10-19  151.0     104.0       NaN
19        60 2023-10-20  162.0     105.0     300.9
20        60 2023-10-21  100.0     106.0     280.0
21        60 2023-10-22  103.0     107.0       NaN
23        60 2023-10-24  134.0       NaN     239.7
24        60 2023-10-25  132.0     110.0     236.9
25        60 2023-10-26  135.0     118.0     278.8
26        60 2023-10-27  137.0     119.0     212.9
27        60 2023-10-28  138.0     121.0     345.9
28        60 2023-10-29  139.0     122.0     345.2
30        60 2023-10-31   94.0     126.0       NaN

In [30]:
import pandas as pd
df = pd.read_csv('mine.csv')
df.loc[7, "Duration"] = 45
print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7         45  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [34]:
import pandas as pd
df = pd.read_csv('mine.csv')
for x in df.index:
    if df.loc[x, 'Duration'] > 120:
       df.loc[x, 'Duration'] = 45
print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7         45  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [47]:
#removing rows
import pandas as pd
df = pd.read_csv('mine.csv')
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.drop(x, inplace = True)
print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [48]:
import pandas as pd
df = pd.read_csv('Sales.csv')
print(df.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
dtype: bool

In [51]:
import pandas as pd
df = pd.read_csv('Sales.csv')
pd.options.display.max_columns = 1999
df.drop_duplicates(inplace = True)
print(df)

   Order ID  Customer Name   Order Date   Product  Quantity  Unit Price  \
0      1001       John Doe   01/01/2024  Widget A      10.0        25.0
1      1002     Jane Smith   01/02/2024  Widget B       5.0        40.0
2      1003            NaN  2024/01/03'  Widget A       NaN        25.0
3      1004  Alice Johnson   04/01/2024  Widget C       3.0         NaN
4      1005      Bob Brown  2024/01/05'  Widget B      10.0        40.0
5      1006       John Doe   06/01/2024  Widget A       4.0        25.0
7      1007     Jane Smith   07/01/2024  Widget C      -6.0        70.0

   Total Revenue
0          250.0
1          200.0
2            NaN
3          210.0
4          400.0
5          100.0
7         -420.0

In [ ]:
import pandas as pd
df = pd.read_csv('mine.csv')
print(df)